version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pos_xpress_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pos_xpress_network
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE:-pos_xpress}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis

  nginx:
    image: nginx:alpine
    container_name: pos_xpress_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - pos_xpress_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: pos_xpress_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-pos_xpress}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-root}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - pos_xpress_network

  redis:
    image: redis:7-alpine
    container_name: pos_xpress_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - pos_xpress_network
    command: redis-server /usr/local/etc/redis/redis.conf

  supervisor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pos_xpress_supervisor
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - pos_xpress_network
    depends_on:
      - mysql
      - redis
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE:-pos_xpress}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - REDIS_HOST=redis

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  pos_xpress_network:
    driver: bridge