<?php

namespace App\Filament\Widgets;

use App\Models\Order;
use App\Models\CashSession;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Illuminate\Support\Carbon;

class CashierStatsWidget extends BaseWidget
{
    protected static ?string $pollingInterval = '30s';

    protected function getStats(): array
    {
        $user = auth()->user();
        $today = Carbon::today();
        
        // Today's orders by current cashier
        $todayOrders = Order::where('store_id', $user->store_id)
            ->where('user_id', $user->id)
            ->whereDate('created_at', $today)
            ->count();
            
        // Today's sales by current cashier
        $todaySales = Order::where('store_id', $user->store_id)
            ->where('user_id', $user->id)
            ->whereDate('created_at', $today)
            ->where('status', 'completed')
            ->sum('total_amount');

        // Current cash session
        $currentSession = CashSession::where('store_id', $user->store_id)
            ->where('user_id', $user->id)
            ->where('status', 'open')
            ->first();

        // Open orders (draft/open status)
        $openOrders = Order::where('store_id', $user->store_id)
            ->whereIn('status', ['draft', 'open'])
            ->count();

        return [
            Stat::make('My Orders Today', $todayOrders)
                ->description('Orders processed by me')
                ->descriptionIcon('heroicon-m-shopping-bag')
                ->color('success'),

            Stat::make('My Sales Today', '$' . number_format($todaySales, 2))
                ->description('Revenue generated by me')
                ->descriptionIcon('heroicon-m-currency-dollar')
                ->color('success'),

            Stat::make('Cash Session', $currentSession ? 'Open' : 'Closed')
                ->description($currentSession ? 'Started at ' . $currentSession->opened_at->format('H:i') : 'No active session')
                ->descriptionIcon('heroicon-m-banknotes')
                ->color($currentSession ? 'success' : 'warning'),

            Stat::make('Open Orders', $openOrders)
                ->description('Orders awaiting completion')
                ->descriptionIcon('heroicon-m-clock')
                ->color($openOrders > 0 ? 'warning' : 'success'),
        ];
    }
}